# Generated by Django 6.0.6 on 2026-07-24 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='cell',
        ),
        migrations.RemoveField(
            model_name='product',
            name='village',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='marketplace.category'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'availability_status'], name='marketplace_categor_ee4c07_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['farmer', '-created_at'], name='marketplace_farmer__e9003d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['verification_status'], name='marketplace_verific_a88483_idx'),
        ),
    ]
