# Generated by Django 6.0.6 on 2026-07-25 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_category_remove_product_cell_remove_product_village_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
